LogLevel info
PageLogFormat

Listen 0.0.0.0:631
Listen /run/cups/cups.sock

Browsing Off
WebInterface Yes
DefaultAuthType Basic

<Location />
  Order allow,deny
  Allow all
</Location>

<Location /admin>
  Order allow,deny
  Allow all
</Location>

<Location /admin/conf>
  AuthType Basic
  Require user @SYSTEM
  Order allow,deny
  Allow all
</Location>

<Policy default>
  <Limit All>
    Order deny,allow
    Allow all
  </Limit>
</Policy>
