domain-needed
bogus-priv
no-resolv
server=1.1.1.1
server=8.8.8.8

listen-address=0.0.0.0
bind-interfaces

domain=corp.lab
expand-hosts

log-queries
log-facility=/var/log/dnsmasq/dnsmasq.log

address=/app.corp.lab/10.10.10.20
address=/app-int.corp.lab/10.10.50.20
address=/db.corp.lab/10.10.30.30
address=/int-endpoint-01.corp.lab/10.10.40.10
address=/user-linux-01.corp.lab/10.10.40.40
address=/dns.corp.lab/10.10.50.50
address=/files.corp.lab/10.10.50.60
address=/proxy.corp.lab/10.10.50.70
address=/ldap.corp.lab/10.10.50.80
address=/print.corp.lab/10.10.50.90
