[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:sshd]
command=/usr/sbin/sshd -D
autorestart=true
priority=10
stdout_logfile=/var/log/supervisor/sshd.out.log
stderr_logfile=/var/log/supervisor/sshd.err.log

[program:rsyslog]
command=/usr/sbin/rsyslogd -n -iNONE
autorestart=true
priority=20
stdout_logfile=/var/log/supervisor/rsyslog.out.log
stderr_logfile=/var/log/supervisor/rsyslog.err.log

[program:gunicorn]
command=/opt/purple-web/venv/bin/gunicorn -w 2 -t 120 -b 0.0.0.0:8080 --access-logfile /var/log/purple-web/access.log --error-logfile /var/log/purple-web/error.log app:APP
directory=/opt/purple-web
autorestart=true
priority=30
stdout_logfile=/var/log/supervisor/gunicorn.out.log
stderr_logfile=/var/log/supervisor/gunicorn.err.log
