[global]
   workgroup = WORKGROUP
   server string = files-int-01
   security = user
   map to guest = never
   log file = /var/log/samba/log.smbd
   max log size = 1000
   logging = file
   server role = standalone server
   smb ports = 445
   disable netbios = yes

[CorpShare]
   path = /srv/shares/corp
   browseable = yes
   read only = no
   guest ok = no
   valid users = analyst ops
   create mask = 0644
   directory mask = 0755
